# Generated by Django 5.0.6 on 2024-06-12 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listen', '0003_alter_speedinstance_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='speedinstance',
            name='true_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 23, 35, 59, 569569, tzinfo=datetime.timezone.utc), verbose_name='true_date'),
            preserve_default=False,
        ),
    ]
